default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mandala_rails_development
  username: <%= ENV.fetch("PGUSER") { ENV["USER"] } %>
  host: localhost

test:
  <<: *default
  database: mandala_rails_test
  username: <%= ENV.fetch("PGUSER") { ENV["USER"] } %>
  host: localhost

production:
  <<: *default
  url: <%= Rails.application.credentials.database_url %>
